const AUTH_USER = "AUTH_USER";
const CLEAN_USER = "CLEAN_USER";

const OPEN_AUTH = "OPEN_AUTH";
const CLOSE_AUTH = "CLOSE_AUTH";

const CHANGE_LOGIN_INPUT = "CHANGE_LOGIN_INPUT";
const CHANGE_PASS_INPUT = "CHANGE_PASS_INPUT";

export {
  AUTH_USER,
  CLEAN_USER,
  OPEN_AUTH,
  CLOSE_AUTH,
  CHANGE_LOGIN_INPUT,
  CHANGE_PASS_INPUT,
};
