const APPROVE_NEWS = "APPROVE_NEWS";
const DELETE_NEWS = "DELETE_NEWS";
const CREATE_NEWS = "CREATE_NEWS";

const CHANGE_CAPTION = "CHANGE_CAPTION";
const CHANGE_TEXT = "CHANGE_TEXT";
const CLEAR_DIALOG = "CLEAR_DIALOG";

const CHANGE_FILTER = "CHANGE_FILTER";

export {
  APPROVE_NEWS,
  DELETE_NEWS,
  CREATE_NEWS,
  CHANGE_CAPTION,
  CHANGE_TEXT,
  CHANGE_FILTER,
  CLEAR_DIALOG,
};
